### ISSUE TITLE
FASMARM throws out of memory errors with too many tests

### ISSUE THREAD

**Issue by bachimusprime** [DenSinH/FuzzARM#4]
I tried generating 100k tests and FASM ran out of memory for some reason, even though I have 24 GB of RAM in my system... It said it was only using 16 MB of RAM for some reason though?

**Comment by DenSinH** [comment]
I think FASMARM is limited in this, I would have to look into it

**Comment by DenSinH** [comment]
Okay judging from this forum thread:

https://board.flatassembler.net/topic.php?t=12800

Fasm doesn't handle large files very well. I don't think it's insanely useful to increase this limit by much though, since a GBA can barely hold 100k in it's ROM space.
